import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer className={styles.footer}>
        Proudly made in
        <Image src="/fav.svg" alt="Vercel Logo" width={32} height={16} href="https://en.wikipedia.org/wiki/Kurdistan"/>
        by Arvin Mostafaei
      </footer>
    </div>
  );
}
